### ISSUE TITLE
Feature suggestion: callback when chatgpt streaming response is complete

### ISSUE THREAD

**Issue by peterlvilim** [CamdenClark/flyboy#13]
This plugin is great! Exactly what I wanted and much better design than the other plugins IMO. Really like how lightweight it is which allows for easy integration into my workflows.

I use nvim as my terminal multiplexer and editor, so I can just have an additional split open where I can ask chatgpt about various topics while working. It is nice to be able to copy and paste in from other splits. I also added an auto command:
```
vim.api.nvim_create_autocmd({ "BufWritePost" }, {
  group = vim.api.nvim_create_augroup("flyboy", { clear = true }),
  pattern = { "*.flyboy" },
  callback = function()
    require('flyboy.chat').send_message()
  end,
})
```
This allows me to save a file for each chat. I can type my questions into the buffer and when I save the buffer my question for the chat gets sent and the reply streams back. I have an organized directory tree of various chats and can grep through them to find old answers. It would be nice to have a callback when the response finishes streaming so that I could write the file again in order to make sure that the latest response is saved.

**Comment by CamdenClark** [comment]
Great feature request! Will give some thought how to do this the right way and get back to you.

Thanks for filing

**Comment by CamdenClark** [comment]
This was easier than I thought it would be -- can you check to see that this configuration setting supports your needs? If so I'll close this.
https://github.com/CamdenClark/flyboy#callback-when-message-finished

**Comment by peterlvilim** [comment]
Just tested and works great!
