### ISSUE TITLE
Support Azure

### ISSUE THREAD

**Issue by CamdenClark** [CamdenClark/flyboy#7]
It would be really nice to support azure deployments of gpt

**Comment by brendonjwong** [comment]
Looks like you'd just need to be able to make these two endpoints configurable?

https://github.com/CamdenClark/flyboy/blob/main/lua/flyboy/openai.lua

- `https://api.openai.com/v1/chat/completions`
- `https://api.openai.com/v1/edits`

**Comment by CamdenClark** [comment]
yeah, true, will do today 😆 

I mistakenly thought a while back that this would require different parameters

**Comment by brendonjwong** [comment]
@CamdenClark I think it may be more than just supporting the endpoints, sadly. The header to provide the API key also seems to be different between the Azure hosted version and Open AI's API

`api-key: $OPEN_API_KEY` vs `Authorization: Bearer $OPEN_API_KEY`

I'm looking for Azure's documentation to link here, but you can see the request shape in our internal Amperity LLM docs.

**Comment by CamdenClark** [comment]
Ah, yeah, that's the issue. I want to make sure I get the configuration right so it's easy to change between them

**Comment by CamdenClark** [comment]
It might be useful to support other headers as well, maybe a header fn that returns a table might be in play here

**Comment by brendonjwong** [comment]
Yeah here's the public documentation

https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line&pivots=rest-api#rest-api

**Comment by brendonjwong** [comment]
And then being able to pass the `api-version` query param is the other key difference, I think.

**Comment by CamdenClark** [comment]
I got this to work! Please update the plugin and see the new section of the docs
https://github.com/CamdenClark/flyboy#alternative-endpoints-azure-openai
